# frozen_string_literal: true

# Configuration for ActiveJobTracker
# This file was generated by the active_job_tracker gem
ActiveJobTracker.configure do |config|
  # Default target value for jobs (default: 100)
  # This represents the total number of items to process in a job
  config.default_target = 100

  # Default cache threshold for progress updates (default: 10)
  # Progress updates are batched until this threshold is reached to reduce database writes
  config.cache_threshold = 10

  # Whether to automatically broadcast changes (default: true)
  # When true, job updates are automatically broadcast via ActionCable
  config.auto_broadcast = true

  # Whether to raise an error when progress increments the current value beyond the target value
  config.raise_error_when_target_exceeded = false

  # Default partial path for rendering job trackers
  # (default: 'active_job_tracker/shared/active_job_tracker')
  config.default_partial = "active_job_tracker/active_job_tracker"

  # Whether to include the style in the job tracker (default: true)
  # When true, the gem's CSS styles are automatically included
  config.include_style = true

  # The turbo stream channel to use for broadcasting job tracker updates
  # (default: 'Turbo::StreamsChannel')
  config.turbo_stream_channel = "Turbo::StreamsChannel"
end
